# Variables

COMPOUNDS_FILENAME = "compounds.csv"
STANDARD_COMPOUNDS_FILENAME = "compounds_std.csv"
MAPPING_FILENAME = "mapping.csv"
VALUES_FILENAME = "values.csv"
TASKS_FILENAME = "tasks.csv"
FOLDS_FILENAME = "folds.csv"
RAW_INPUT_FILENAME = "raw_input"

PARAMETERS_FILE = "parameters.json"
INPUT_SCHEMA_FILENAME = "input_schema.json"

MAPPING_ORIGINAL_COLUMN = "orig_idx"
MAPPING_DEDUPE_COLUMN = "uniq_idx"
COMPOUND_IDENTIFIER_COLUMN = "compound_id"
USER_COMPOUND_IDENTIFIER_COLUMN = "orig_compound_id"
SMILES_COLUMN = "smiles"
STANDARD_SMILES_COLUMN = "standard_smiles"
DATE_COLUMN = "date"
QUALIFIER_COLUMN = "qualifier"
VALUES_COLUMN = "value"
GROUP_COLUMN = "group"
DIRECTION_COLUMN = "direction"
AUXILIARY_TASK_COLUMN = "clf_aux"